# Generated by Django 5.2.4 on 2025-10-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='cidade',
            field=models.CharField(default='desconhecida', max_length=100),
            preserve_default=False,
        ),
    ]
